apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sinelog-logs-pvc
  namespace: sinelog
  labels:
    app: sinelog
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
